#!/usr/bin/env python3
import sys
import os
import re

# Resolve paths
tools_dir = os.path.dirname(os.path.abspath(__file__))
musax_dir = os.path.dirname(tools_dir)
jukebox_dir = os.path.join(musax_dir, "src", "jukebox")
tests_dir = os.path.join(jukebox_dir, "SRC", "TESTS")
tmp_dir = os.path.join(jukebox_dir, "TMP")

# Ensure tools_dir is in path to import msl2z8a
if tools_dir not in sys.path:
    sys.path.append(tools_dir)

from msl2z8a import msl2z8a

def parse_msl(filepath):
    """Parses a .msl file using regex to extract metadata and FX."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    title_match = re.search(r'@TITLE\s+"([^"]+)"', content, re.IGNORECASE)
    author_match = re.search(r'@AUTHOR\s+"([^"]+)"', content, re.IGNORECASE)
    ns_match = re.search(r'@(?:NAMESPACE|MODULE)\s+([A-Za-z0-9_]+)', content, re.IGNORECASE)
    
    # Extract FX blocks
    fx_names = re.findall(r'@FX\s*\(\s*([A-Za-z0-9_]+)\s*\)', content, re.IGNORECASE)
    
    title = title_match.group(1) if title_match else os.path.splitext(os.path.basename(filepath))[0].replace('_', ' ').title()
    author = author_match.group(1) if author_match else "Unknown"
    namespace = ns_match.group(1).upper() if ns_match else os.path.splitext(os.path.basename(filepath))[0].upper()
    
    return {
        'filepath': filepath,
        'filename': os.path.basename(filepath),
        'title': title,
        'author': author,
        'namespace': namespace,
        'fxs': fx_names
    }

def main():
    print("MusaX Playlist Generator starting...")
    os.makedirs(tmp_dir, exist_ok=True)
    
    # 1. Gather all files
    # First is always shalomcastle from examples
    songs = []
    shalom_path = os.path.join(musax_dir, "examples", "msl", "shalomcastle.msl")
    if os.path.exists(shalom_path):
        songs.append(parse_msl(shalom_path))
        
    # Then search tests folder
    test_files = []
    if os.path.exists(tests_dir):
        for f in sorted(os.listdir(tests_dir)):
            if f.endswith('.msl'):
                test_files.append(os.path.join(tests_dir, f))
                
    for filepath in test_files:
        # Don't add duplicate shalomcastle if it's somehow in tests
        if os.path.basename(filepath) != "shalomcastle.msl":
            songs.append(parse_msl(filepath))
            
    # 2. Compile each file to TMP/
    for song in songs:
        out_name = os.path.splitext(song['filename'])[0] + ".Z8A"
        out_path = os.path.join(tmp_dir, out_name)
        print(f"Compiling {song['filename']} to {out_name}...")
        msl2z8a(song['filepath'], out_path)
        
    # 3. Generate PLAYLIST.Z8A
    playlist_path = os.path.join(tmp_dir, "PLAYLIST.Z8A")
    print(f"Generating playlist at {playlist_path}...")
    
    with open(playlist_path, 'w', encoding='utf-8') as f:
        f.write("; ==========================================\n")
        f.write("; AUTOGENERATED PLAYLIST - DO NOT EDIT MANUALLY\n")
        f.write("; ==========================================\n\n")
        
        f.write("; --- SONG BINARY INCLUSIONS\n")
        for song in songs:
            out_name = os.path.splitext(song['filename'])[0] + ".Z8A"
            f.write(f'                INCLUDE "TMP/{out_name}"\n')
        f.write("\n")
        
        f.write(f"; --- SONG COUNT CONSTANT\n")
        f.write(f"SONGCOUNT       EQU     {len(songs)}\n\n")
        
        f.write("; --- DYNAMIC SONG TABLE\n")
        f.write("; Format: [HEADER_PTR (2b), NAME_CYAN_PTR (2b), NAME_WHITE_PTR (2b), SHORT_NAME_PTR (2b)]\n")
        f.write("SONGTBL:\n")
        for i, song in enumerate(songs, 1):
            f.write(f"                DEFW    {song['namespace']}.HEADER, SNG{i}_CYAN, SNG{i}_WHITE, SNG{i}_SHORT\n")
        f.write("\n")
        
        f.write("; --- SONG STRINGS DEFINITIONS\n")
        for i, song in enumerate(songs, 1):
            # Clean up the name for list representation
            name_clean = song['title'].upper()
            if len(name_clean) > 13:
                name_clean = name_clean[:13]
            else:
                name_clean = name_clean.ljust(13)
                
            name_lower = song['title'].lower()
            if len(name_lower) > 13:
                name_lower = name_lower[:13]
            else:
                name_lower = name_lower.ljust(13)
                
            short_name = song['title'].upper().replace(' ', '')
            if len(short_name) > 6:
                short_name = short_name[:6]
            else:
                short_name = short_name.ljust(6)
                
            f.write(f'SNG{i}_CYAN:      DEFB    "{name_lower}", 0\n')
            f.write(f'SNG{i}_WHITE:     DEFB    "{name_clean}", 0\n')
            f.write(f'SNG{i}_SHORT:     DEFB    "{short_name}", 0\n')
        f.write("\n")
        
        # Build FX list
        fxs = []
        for song in songs:
            for idx, fx in enumerate(song['fxs']):
                fxs.append({
                    'namespace': song['namespace'],
                    'name': fx,
                    'index': idx
                })
                
        f.write(f"; --- FX COUNT CONSTANT\n")
        f.write(f"FXCOUNT         EQU     {len(fxs)}\n\n")
        
        f.write("; --- DYNAMIC FX TABLE\n")
        f.write("; Format: [FX_TABLE_PTR (2b), FX_INDEX (2b), NAME_CYAN_PTR (2b), NAME_WHITE_PTR (2b), SHORT_NAME_PTR (2b)]\n")
        f.write("FXTBL:\n")
        for i, fx in enumerate(fxs, 1):
            f.write(f"                DEFW    {fx['namespace']}.FX_TABLE, {fx['index']}, FX{i}_CYAN, FX{i}_WHITE, FX{i}_SHORT\n")
        f.write("\n")
        
        f.write("; --- FX STRINGS DEFINITIONS\n")
        for i, fx in enumerate(fxs, 1):
            name_clean = fx['name'].upper()
            if len(name_clean) > 11:
                name_clean = name_clean[:11]
            else:
                name_clean = name_clean.ljust(11)
                
            name_lower = fx['name'].lower()
            if len(name_lower) > 11:
                name_lower = name_lower[:11]
            else:
                name_lower = name_lower.ljust(11)
                
            short_name = fx['name'].upper().replace(' ', '')
            if len(short_name) > 6:
                short_name = short_name[:6]
            else:
                short_name = short_name.ljust(6)
                
            f.write(f'FX{i}_CYAN:       DEFB    "{name_lower}", 0\n')
            f.write(f'FX{i}_WHITE:      DEFB    "{name_clean}", 0\n')
            f.write(f'FX{i}_SHORT:      DEFB    "{short_name}", 0\n')
            
    print("Playlist generated successfully!")

if __name__ == "__main__":
    main()
