from msl_parser import MSLParser, SetTempo
from msl_codegen import CodeGenerator

class MSLCompiler:
    def __init__(self):
        self.parser = MSLParser()
        self.generator = CodeGenerator()

    def compile(self, song_name: str, channel_a_mml: str, channel_b_mml: str, channel_c_mml: str) -> str:
        # 1. Parse each channel
        events_a = self.parser.parse(channel_a_mml)
        events_b = self.parser.parse(channel_b_mml)
        events_c = self.parser.parse(channel_c_mml)

        # Find BPM
        bpm_step = "#12C0" # default
        all_events = events_a + events_b + events_c
        for event in all_events:
            if isinstance(event, SetTempo):
                bpm_step = f"#{event.bpm_step:04X}"
                break

        # Remove tempo events from channels
        events_a = [e for e in events_a if not isinstance(e, SetTempo)]
        events_b = [e for e in events_b if not isinstance(e, SetTempo)]
        events_c = [e for e in events_c if not isinstance(e, SetTempo)]

        # 2. Generate the full Z80 file content
        z80_code = f"""; -- {song_name} - Generated by MSLCompiler --

"""
        
        # --- Generate header ---
        header_label = f"{song_name.upper()}_HDR"
        cha_label = f"{song_name.upper()}_CHA"
        chb_label = f"{song_name.upper()}_CHB"
        chc_label = f"{song_name.upper()}_CHC"

        z80_code += f"{header_label}:\n"
        z80_code += f"    DEFW    {bpm_step}, {cha_label}\n"
        z80_code += f"    DEFW    {bpm_step}, {chb_label}\n"
        z80_code += f"    DEFW    {bpm_step}, {chc_label}\n"
        z80_code += f"    DEFW    0\n\n"
        
        # --- Generate channel A ---
        z80_code += f"; --- CHANNEL A ---\n"
        z80_code += f"{cha_label}:\n"
        z80_code += self.generator.generate(events_a)
        
        # --- Generate channel B ---
        z80_code += f"; --- CHANNEL B ---\n"
        z80_code += f"{chb_label}:\n"
        z80_code += self.generator.generate(events_b)

        # --- Generate channel C ---
        z80_code += f"; --- CHANNEL C ---\n"
        z80_code += f"{chc_label}:\n"
        z80_code += self.generator.generate(events_c)

        return z80_code

def main():
    compiler = MSLCompiler()
    
    # Example MML for 3 channels
    mml_a = "L4 C E G @T#0600"
    mml_b = "L4 E G B"
    mml_c = "L4 G B > D"
    
    z80_file_content = compiler.compile("MY_SONG", mml_a, mml_b, mml_c)
    
    print("--- Generated Z80 File ---")
    print(z80_file_content)

if __name__ == "__main__":
    main()
